config/routes.rb
Rails.application.routes.draw do
  resources :store_visits
  resources :products
  resources :retail_stores
  resources :sales_reps
  devise_for :users
  resources :users

  root to: 'page#index'
end

app/models/retail_store.rb
class RetailStore < ApplicationRecord
  has_many :store_visits
  belongs_to :sales_rep, optional: true
end

app/controllers/retail_stores_controller.rb
class RetailStoresController < ApplicationController
  load_and_authorize_resource
  before_action :set_retail_store, only: [:show, :edit, :update, :destroy]

  # GET /retail_stores
  # GET /retail_stores.json
  def index
    @retail_stores = RetailStore.all
  end

  # GET /retail_stores/1
  # GET /retail_stores/1.json
  def show
  end

  # GET /retail_stores/new
  def new
    @retail_store = RetailStore.new
  end

  # GET /retail_stores/1/edit
  def edit
  end

  # POST /retail_stores
  # POST /retail_stores.json
  def create
    @retail_store = RetailStore.new(retail_store_params)

    respond_to do |format|
      if @retail_store.save
        format.html { redirect_to @retail_store, notice: 'Retail store was successfully created.' }
        format.json { render :show, status: :created, location: @retail_store }
      else
        format.html { render :new }
        format.json { render json: @retail_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /retail_stores/1
  # PATCH/PUT /retail_stores/1.json
  def update
    respond_to do |format|
      if @retail_store.update(retail_store_params)
        format.html { redirect_to @retail_store, notice: 'Retail store was successfully updated.' }
        format.json { render :show, status: :ok, location: @retail_store }
      else
        format.html { render :edit }
        format.json { render json: @retail_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /retail_stores/1
  # DELETE /retail_stores/1.json
  def destroy
    @retail_store.destroy
    respond_to do |format|
      format.html { redirect_to retail_stores_url, notice: 'Retail store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_retail_store
      @retail_store = RetailStore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def retail_store_params
      params.require(:retail_store).permit(:name, :location)
    end
end

app/helpers/retail_stores_helper.rb
module RetailStoresHelper
end

app/views/retail_stores/_form.html.haml
.row
  .col-md-6
    = simple_form_for(@retail_store) do |f|
      = f.error_notification
      = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

      .form-inputs
        .form-group
          = f.input :name, input_html: {class: 'form-control'}
        .form-group
          = f.input :location, input_html: {class: 'form-control'}

      .form-actions
        = f.button :submit, class: 'btn btn-primary'

app/views/retail_stores/edit.html.haml
%h1 Editing Retail Store

= render 'form'

= link_to 'Show', @retail_store, class: 'btn'
\|
= link_to 'Back', retail_stores_path, class: 'btn'

app/views/retail_stores/index.html.haml
%h1 Listing Retail Stores
%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Location
      %th
      %th
      %th

  %tbody
    - @retail_stores.each do |retail_store|
      %tr
        %td= retail_store.name
        %td= retail_store.location
        %td= link_to 'Show', retail_store
        %td= link_to 'Edit', edit_retail_store_path(retail_store)
        %td= link_to 'Destroy', retail_store, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Retail store', new_retail_store_path, class: 'btn btn-primary'

app/views/retail_stores/new.html.haml
%h1 New Retail Store

= render 'form'

= link_to 'Back', retail_stores_path, class: 'btn'

app/views/retail_stores/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @retail_store.name
%p
  %b Location:
  = @retail_store.location

%h3 Store Visits

%table.table.table-striped
  %thead
    %tr
      %th Sales Rep
      %th Verification Date
      %th

  %tbody
    - @retail_store.store_visits.each do |store_visit|
      %tr
      %td= store_visit.sales_rep.name if store_visit.sales_rep
      %td= store_visit.verification_date
      %td= link_to 'Show', store_visit

= link_to 'Edit', edit_retail_store_path(@retail_store), class: 'btn'
\|
= link_to 'Back', retail_stores_path, class: 'btn'