config/routes.rb
Rails.application.routes.draw do
  resources :store_visits
  resources :products
  resources :retail_stores
  resources :sales_reps
  devise_for :users
  resources :users

  root to: 'page#index'
end

app/models/store_visit.rb
class StoreVisit < ApplicationRecord
  belongs_to :sales_rep
  belongs_to :retail_store
  has_many :product_verifications

  accepts_nested_attributes_for :product_verifications, allow_destroy: true
end

app/controllers/store_visits_controller.rb
class StoreVisitsController < ApplicationController
  load_and_authorize_resource
  before_action :set_store_visit, only: [:show, :edit, :update, :destroy]

  # GET /store_visits
  # GET /store_visits.json
  def index
    if current_user.admin?
      @store_visits = StoreVisit.all
    else
      @store_visits = current_user.sales_rep.store_visits
    end
  end

  # GET /store_visits/1
  # GET /store_visits/1.json
  def show
  end

  # GET /store_visits/new
  def new
    @store_visit = StoreVisit.new

    @store_visit.product_verifications.build
  end

  # GET /store_visits/1/edit
  def edit
  end

  # POST /store_visits
  # POST /store_visits.json
  def create
    @store_visit = StoreVisit.new(store_visit_params)

    respond_to do |format|
      if @store_visit.save
        format.html { redirect_to @store_visit, notice: 'Store visit was successfully created.' }
        format.json { render :show, status: :created, location: @store_visit }
      else
        format.html { render :new }
        format.json { render json: @store_visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /store_visits/1
  # PATCH/PUT /store_visits/1.json
  def update
    respond_to do |format|
      if @store_visit.update(store_visit_params)
        format.html { redirect_to @store_visit, notice: 'Store visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @store_visit }
      else
        format.html { render :edit }
        format.json { render json: @store_visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /store_visits/1
  # DELETE /store_visits/1.json
  def destroy
    @store_visit.destroy
    respond_to do |format|
      format.html { redirect_to store_visits_url, notice: 'Store visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store_visit
      @store_visit = StoreVisit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_visit_params
      params.require(:store_visit).permit(:retail_store_id, :sales_rep_id, :verification_date, product_verifications_attributes: [:id, :product_id, :unit_count])
    end
end

app/helpers/store_visits_helper.rb
module StoreVisitsHelper
end

app/views/store_visits/_form.html.haml
.row
  .col-md-6
    = simple_form_for(@store_visit) do |f|
      = f.error_notification
      = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

      .form-inputs
        .form-group
          = f.input :retail_store_id, as: :select, collection: RetailStore.all, input_html: {class: 'form-control'}
        - if current_user.admin?
          .form-group
            = f.input :sales_rep_id, as: :select, collection: SalesRep.all, input_html: {class: 'form-control'}
        - elsif (current_user.sales_rep)
          = f.input :sales_rep_id, as: :hidden, :input_html => { :value => current_user.sales_rep.id }

        .form-group
          = f.input :verification_date, input_html: {class: 'form-control'}

        %hr
        %h3 Product Verifications

        #product_verifications
          = f.simple_fields_for :product_verifications do |v|
            = render 'product_verification_fields', :f => v
            .links
              = link_to_add_association raw('<button type="button" class="btn btn-success btn-small">Add</button>'), f, :product_verifications

      .form-actions.pt-5
        = f.button :submit, class: 'btn btn-primary'

app/views/store_visits/_product_verification_fields.html.haml
.nested-fields
  .form-group
    = f.input :product_id, :as => :select,collection: Product.all, input_html: {class: 'form-control'}
  .form-group
    = f.input :unit_count, input_html: {class: 'form-control'}
  = link_to_remove_association raw('<button type="button" class="btn btn-danger btn-sm">X</button>'), f
.clearfix
%hr

app/views/store_visits/edit.html.haml
%h1 Editing Store Visit

= render 'form'

= link_to 'Show', @store_visit, class: 'btn'
\|
= link_to 'Back', store_visits_path, class: 'btn'

app/views/store_visits/index.html.haml
%h1 Listing Store Visits

.row
  .col-md-4.mb-2
    %input.form-control#search_store_visits{type:"text", placeholder:"Search..."}

%table.table.table-striped#store_visits_table
  %thead
    %tr
      %th Retail store
      %th Sales rep
      %th Verification Date
      %th
      %th
      %th

  %tbody
    - @store_visits.each do |store_visit|
      %tr
        %td= store_visit.retail_store.name if store_visit.retail_store
        %td= store_visit.sales_rep.name if store_visit.sales_rep
        %td= store_visit.verification_date
        %td= link_to 'Show', store_visit
        %td= link_to 'Edit', edit_store_visit_path(store_visit)
        %td= link_to 'Destroy', store_visit, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Store visit', new_store_visit_path, class: 'btn btn-primary'

app/views/store_visits/new.html.haml
%h1 New Store Visit

= render 'form'

= link_to 'Back', store_visits_path, class: 'btn'

app/views/store_visits/show.html.haml
%p#notice= notice

%p
  %b Retail store:
  = @store_visit.retail_store.name
%p
  %b Sales rep:
  = @store_visit.sales_rep.name if @store_visit.sales_rep
%p
  %b Verification date:
  = @store_visit.verification_date

%h3 Product Verifications

%table.table.table-striped
  %thead
    %tr
      %th Product
      %th Count

  %tbody
    - @store_visit.product_verifications.each do |verification|
      %tr
        %td= verification.product.name
        %td= verification.unit_count
      

= link_to 'Edit', edit_store_visit_path(@store_visit), class: 'btn'
\|
= link_to 'Back', store_visits_path, class: 'btn'