config/routes.rb
Rails.application.routes.draw do
  resources :store_visits
  resources :products
  resources :retail_stores
  resources :sales_reps
  devise_for :users
  resources :users

  root to: 'page#index'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_verifications
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
.row
  .col-md-6
    = simple_form_for(@product) do |f|
      = f.error_notification
      = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

      .form-inputs
        .form-group
          = f.input :name, input_html: {class: 'form-control'}

      .form-actions
        = f.button :submit, class: 'btn btn-primary'

app/views/products/edit.html.haml
%h1 Editing Product

= render 'form'

= link_to 'Show', @product, class: 'btn'
\|
= link_to 'Back', products_path, @product, class: 'btn'

app/views/products/index.html.haml
%h1 Listing Products

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @products.each do |product|
      %tr
        %td= product.name
        %td= link_to 'Show', product
        %td= link_to 'Edit', edit_product_path(product)
        %td= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Product', new_product_path, class: 'btn btn-primary'

app/views/products/new.html.haml
%h1 New Product

= render 'form'

= link_to 'Back', products_path, class: 'btn'

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @product.name

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path